### ISSUE TITLE
Not all network_provider: nm options are supported.

### ISSUE THREAD

**Issue by hartsjc** [linux-system-roles/network#10]
Many of the nmcli connection show <connection>  options available do not appear to be supported. Even several of them that supported in nm-connection-editor don't appear to be present...

Doing a quick look think some examples are:
```
connection.lld
connection.autoconnect <-------------- in nm-connection-editor (general)
connection.autoconnect-priority <----- in nm-connection-editor (general)
connection.autoconnect-retries
connection.zone <--------------------- in nm-connection-editor (general)

802-3-ethernet.cloned-mac-address <--- in nm-connection-editor (ethernet)
802-3-ethernet.mtu <------------------ in nm-connection-editor (ethernet)
802-3-ethernet.wake-on-lan-password <- in nm-connection-editor (ethernet)
802-3-ethernet.auto-negotiate <------- in nm-connection-editor (ethernet)
802-3-ethernet.speed <---------------- in nm-connection-editor (ethernet)
802-3-ethernet.duplex <--------------- in nm-connection-editor (ethernet)

ipv4.may-fail <----------------------- in nm-connection-editor (ipv4)
ipv4.ignore-auto-routes <------------- in nm-connection-editor (ipv4 routes)
ipv4.ignore-auto-dns
ipv4.never-default

ipv6.may-fail<----------------------- in nm-connection-editor (ipv6)
ipv6.ignore-auto-routes <------------- in nm-connection-editor (ipv6 routes)
ipv6.ignore-auto-dns
ipv6.never-default
```

Then some DHCP options:
```
  ipv4.dhcp-client-id
  ipv4.dhcp-timeout
  ipv4.dhcp-send-hostname
  ipv4.dhcp-hostname
  ipv4.dhcp-fqdn
  ipv6.dhcp-send-hostname
  ipv6.dhcp-hostname
```

**Comment by thom311** [comment]
Note that `nm-connection-editor` also doesn't support all options of NetworkManager either. The reason for that is that nobody invested the work, and not to clutter the GUI with advanced options. There is a trade-off regarding what is suitable to expose in the GUI.

Anyway, the role only supports a very small set of options because: 

  - nobody requested the feature yet, and thus nobody implemented it.

  - optimally, the same playbook can be used with the different `network_provider` (currently only `nm` and `initscripts` is supported). It is a bit of a problem, if certain options work only with one of the `network_provider`, or if they behave differently. Not much that can be done about that though.


I am closing this issue because it's too wide. Open issues for specific options you want, best with an explanation why it is required. Or even better, open a pull request ;-)

Thanks.
