### ISSUE TITLE
not idempotent against /etc/resolv.conf with initscripts provider

### ISSUE THREAD

**Issue by marcoskv** [linux-system-roles/network#125]
I tested the role with initscripts network provider in CentOS 7.6.

If I change the ip->dns variable, /etc/resolv.conf is rewritten with the new dns values, but the dns_search value is always appended, never overwritten.

After a few executions of the role, here is the resulting resolv.conf

```
search domain.org domain.org domain.org domain.org domain.org
nameserver 192.168.121.2
nameserver 192.168.121.3
```

Moreover, it is a pity that using this role the diff feature of ansible does not work. It would be nice to see the changes applied to the configuration files.

**Comment by thom311** [comment]
The role doesn't write resolv.conf, it merely calls ifup.

Since initscripts don't provide any other API beyond that, fixing this would require the role to re-implement the functionality instead of calling ifup.

I don't think that's the right approach nor worth the effort. initscritps are simple scripts that do something. It's easy to create situations where they do the wrong thing. In the end, it's the users responsibility to call ifup/ifdown in the right order. In fact, that is so easy to result in wrong things, that it's usually better to issue `service restart network`, or even better reboot.

The role also doesn't know whether it should call ifdown before ifup (that's because neither the role know initscripts really know which scripts was called last, and whether ifdown is due).

I don't know how to fix this. Suggestions are welcome :)

**Comment by marcoskv** [comment]
Many thanks for the detailed explanation.

I fully agree with you, it does not make sense to reinvent the wheel and rewrite the ifup functionality within this ansible role.

Probably the best would be to change/upgrade the network provider to NetworkManager, but in my team we prefer to disable that service from our servers ;-)

**Comment by tyll** [comment]
@marcoskv thank you for your contribution. I understand that you agree that this does not need any further action, therefore I will close this issue. If you disagree, please let me know and re-open this issue (if possible). If you would like to provide RFE for NetworkManager so you do not need to disable it anymore, please reach out to the development team at https://mail.gnome.org/mailman/listinfo/networkmanager-list
