### ISSUE TITLE
CI failures on Fedora 32

### ISSUE THREAD

**Issue by cathay4t** [linux-system-roles/network#301]
Taking notes for CI failure due to known bugs:

 * Service is in unknown state: https://github.com/ansible/ansible/issues/71528
 * Check which services are running: https://github.com/ansible/ansible/issues/69302

**Comment by pcahyna** [comment]
@cathay4t Regarding the first. Was this present in original Fedora 32 and fixed in an update? Or vice-versa, was it working in original Fedora 32 and broken in an update? Or is it broken both in original F432 release and the current version? I am asking because I would like to know whether the ongoing change to use most recent updated composes instead of the original release fixes the issue, introduces the issue, or makes no difference.

Regarding the second. That was fixed a months ago. Did it reappear?

**Comment by richm** [comment]
Were these problems only with ansible 2.8?  We recently dropped support in CI for fedora 32 with ansible 2.8

**Comment by cathay4t** [comment]
Closing as CI has Fedora 32 with ansible 2.8 any more.
