### ISSUE TITLE
Failure during package installation on Rocky 8

### ISSUE THREAD

**Issue by rumline** [linux-system-roles/network#441]
Problem:  Playbook fails during the linux-system-tools.network role during the Package Installation phase.

Controller Versions:
- Red Hat Enterprise Linux release 8.5 (Ootpa)
- Red Hat Automation Platform:  4.1.0
- ansible-core:  2.12.0
- ansible-runner:  2.1.1
- python 3.8.8

Target Versions:
- Rocky Linux release 8.5 (Green Obsidian)
- python 3.6.8

Attached playbook and facts from the host.

Please advise

[linux-system-tools.network_error.txt](https://github.com/linux-system-roles/network/files/7694421/linux-system-tools.network_error.txt)
[ip-change-playbook.txt](https://github.com/linux-system-roles/network/files/7694426/ip-change-playbook.txt)
[target_facts_json.txt](https://github.com/linux-system-roles/network/files/7694428/target_facts_json.txt)
[target_facts_yml.txt](https://github.com/linux-system-roles/network/files/7694429/target_facts_yml.txt)

**Comment by richm** [comment]
What version of this role are you using?

**Comment by rumline** [comment]
From the changelog:  [1.4.0] - 2021-08-10

**Comment by richm** [comment]
> From the changelog: [1.4.0] - 2021-08-10

That version still uses json_query, so you'll have to install jmespath e.g. `pip install jmespath`.

**Comment by rumline** [comment]
jmespath was installed on the AWX controller but not on the target.  Installed jmespath on the target and got the same error.  Could this have to do with the fact that AWX is actually running in containers on the controller?

**Comment by richm** [comment]
> jmespath was installed on the AWX controller but not on the target.

That is correct - filters are run on the controller, not on the target (as oppposed to modules, which are run on the target).

> Installed jmespath on the target and got the same error. Could this have to do with the fact that AWX is actually running in containers on the controller?

Then I guess you'll need to figure out how to install jmespath in the container.

> 
> Is there a higher version of the tools? 1.4.0 is the latest tag in github.

@cathay4t @liangwen12year Are you guys planning to do another network release soon?

Alternately - I regularly release roles to github and galaxy, for all of the roles except network, because it seems that your team prefers to do your own releases on your own schedule.  For all of the other roles, there is no release schedule - I release when there is any new feature available, and create a version number based on semantic versioning and the changes, and construct the Release Notes from the git commit messages.  I could also do this for the network role.

**Comment by liangwen12year** [comment]
Hi richm, I am planning to do another upsteam network role release by the end of this Thursday (12/16/2021).

**Comment by tyll** [comment]
> Alternately - I regularly release roles to github and galaxy, for all of the roles except network, because it seems that your team prefers to do your own releases on your own schedule. For all of the other roles, there is no release schedule - I release when there is any new feature available, and create a version number based on semantic versioning and the changes, and construct the Release Notes from the git commit messages. I could also do this for the network role.

This would be great. I would like to see new releases every two weeks (if there are any changes other than the tests).

**Comment by liangwen12year** [comment]
The network role 1.5.0 was released to github and galaxy.

**Comment by liangwen12year** [comment]
Close it for now, if the issue persists, please reopen it.
