### ISSUE TITLE
when using initscripts, brctl needs to be present to configure bridges

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#68]
The initscripts backend requires brctl for bridge support, however brctl might be missing on for example on CentOS6 images:

```
TASK [linux-system-roles.network : Configure networking connection profiles] ***
task path: /tmp/tmptjhidpez/tests/roles/linux-system-roles.network/tasks/main.yml:21
 [WARNING]: [003] <info>  #0, state:up, "LSR-TST-br31": add ifcfg-rh profile
"LSR-TST-br31"
 [WARNING]: [004] <info>  #0, state:up, "LSR-TST-br31": up connection LSR-TST-
br31 (not-active)
 [WARNING]: [005] <info>  #0, state:up, "LSR-TST-br31": call `ifup LSR-TST-
br31`: rc=1, out="Bridge support not available: brctl not found ", err=""
 [WARNING]: [006] <error> #0, state:up, "LSR-TST-br31": call `ifup LSR-TST-
br31` failed with exit status 1
fatal: [/cache/CentOS-6-x86_64-GenericCloud-1804_02.qcow2c]: FAILED! => {"changed": true, "msg": "error: call `ifup LSR-TST-br31` failed with exit status 1"}
	to retry, use: --limit @/tmp/tmptjhidpez/tests/tests_bridge.retry
```

I guess we have these options:

* Always install brctl when the initscripts backend is used via a task in the role
* Only install it in the module when bridges need to be installed
* Create a new module to install missing packages after analysing the network state

**Comment by thom311** [comment]
other option:

- do nothing. A user who needs it, can make sure that brctl is installed. Either, he can modify the role to drag in the package, or he can run another playbook first, that installs the package. I am not saying, that we should do nothing, but the issue seems only an inconvenience, that the user can work around already.

Option 3 (Create a new module to install missing packages after analysing the network state) sound optimal (but most effort).
It might be solvable with an action-plugin (that is, a module that runs on the controller and delegates to another module -- I think these are called "action plugin" (??)), that uses the ArgValidator to parse the input. It should be relatively straight forward to parse the `network_connections` and figure out what is needed.

**Comment by pcahyna** [comment]
I think one does not need a custom action plugin or another custom plugin. Is the json_query filter sufficient to parse `network_connections`? https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter

**Comment by pcahyna** [comment]
So, fifth option: parse `network_connections` in the role and use the `package` (or `yum`) module to install the required package if needed.
I think the first option is a bit suboptimal: one should not need to install packages that one does not need.
Second is not the right design: our module should not install packages IMO (there are modules to do that already).
Third: ditto
Fourth: not good for the user as the role should isolate users exactly from this kind of complexity.

**Comment by pcahyna** [comment]
So far it seems to not be so complex, see #72 . Of course, if it turns out to be more complex than that, writing a module which reuses the current parser is a good option.
