### ISSUE TITLE
Not all network_provider: initscripts options are supported, some crucial for enterprise.

### ISSUE THREAD

**Issue by hartsjc** [linux-system-roles/network#9]
Many of the /etc/sysconfig/network-scripts/ifcfg-<interface-name> options documented in  /usr/share/doc/initscripts-*/sysconfig.txt  do not appear to be supported.  Some key/crucial ones that appear to be missing for enterprise servers are:
```
1. ETHTOOL_OPTS
2. LINKDELAY
3. IPV4_FAILURE_FATAL
```

Some others may include (have not tested to validate missing, just grep of code):
```
ARPCHECK
DHCLIENTARGS
DHCLIENT_IGNORE_GATEWAY
DHCP_FQDN
DHCP_HOSTNAME
DHCPRELEASE
HOTPLUG
MACADDR
NETMASK
NO_DHCP_HOSTNAME
NOZEROCONF
PEERDNS
PERSISTENT_DHCLIENT
SCOPE
SRCADDR
USERCTL
WINDOW
ZONE
```

**Comment by thom311** [comment]
We probably won't ever support all options that either provider (initscripts or nm) supports.

For one, the provider (backends) may not support all options that another provider implement. It is possible, and sometimes reasonable to add a feature, even if it is not supported with every provider. However, unless there are good justifications to do it, we may not do that.

Also, some features may not be common enough to justify the work to add them.

I am closing this issue. We should open separate issues for each feature/option. That way, the issues themselves have a smaller and better defined scope, instead of being open-ended. 

Thank you.
